[package]
name = "ainvm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iota = "0.2"

[lib]
name="op_codes"
path="src/op_codes.rs"